services:
  searcher0:
    image: searcher-worker
    ports:
      - 8000:80
    volumes:
      - ../data:/code/data
  searcher1:
    image: searcher-worker
    ports:
      - 8001:80
    volumes:
      - ../data:/code/data
